<?php

use App\Http\Controllers\API\V1\Admin\Coursecontroller;
use App\Http\Controllers\API\V1\Admin\CourseSectionControoler;
use App\Http\Controllers\API\V1\Student\CreateEnrollmentController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\API\V1\Admin\UserController;
use App\Http\Controllers\API\V1\Auth\AuthController;
use App\Http\Controllers\API\V1\Auth\PasswardResetController;
use App\Http\Controllers\API\V1\Student\ProfileContoller;
use App\Http\Controllers\API\V1\Faculty\MaterialController;
use App\Http\Controllers\API\V1\Faculty\GradeUploadController;
use App\Http\Controllers\API\V1\Admin\UploadCourseGradeController;
use App\Http\Controllers\API\V1\Admin\AnnouncementController;
Route::post('/users', [UserController::class, 'store'])->middleware(['api', 'auth:sanctum', 'role:admin']);
Route::post('edit-user/{id}',[UserController::class, 'edit'])->middleware(['api', 'auth:sanctum', 'role:admin']);
Route::post('delete-user/{id}',[UserController::class, 'delete'])->middleware(['api', 'auth:sanctum', 'role:admin']);
Route::post('/login', [AuthController::class, 'login']);
Route::post('/logout/{id}', [AuthController::class, 'logout'])->middleware(['api', 'auth:sanctum']);
Route::post('/forget-password', [PasswardResetController::class, 'forget']);
Route::post('/reset-password', [PasswardResetController::class, 'reset']);
Route::post('/edit-profile/{id}', [ProfileContoller::class, 'update'])->middleware(['api', 'auth:sanctum', 'role:student']);
Route::post('/course-create',[Coursecontroller::class,'store'])->middleware(['api','auth:sanctum','role:admin']);
 Route::get('/courses',[Coursecontroller::class,'index'])->middleware(['api','auth:sanctum','role:admin']);
 Route::get('/courses/{id}',[Coursecontroller::class,'show'])->middleware(['api','auth:sanctum']);
 Route::post('/course-update/{id}',[Coursecontroller::class,'update'])->middleware(['api','auth:sanctum','role:admin']);
 Route::post('/course-delete/{id}',[Coursecontroller::class,'destroy'])->middleware(['api','auth:sanctum','role:admin']);
 Route::post('course-section-create',[CourseSectionControoler::class,'store'])->middleware(['api','auth:sanctum','role:admin']);
 Route::get('course-sections',[CourseSectionControoler::class,'index'])->middleware(['api','auth:sanctum','role:admin']);
Route::get('course-section/{id}',[CourseSectionControoler::class,'show'])->middleware(['api','auth:sanctum','role:admin']);
Route::post('course-section-update/{id}',[CourseSectionControoler::class,'update'])->middleware(['api','auth:sanctum','role:admin']);
Route::post('course-section-delete/{id}',[CourseSectionControoler::class,'destroy'])->middleware(['api','auth:sanctum','role:admin']);
Route::get('course-sections-current',[CourseSectionControoler::class,'currentSections'])->middleware(['api','auth:sanctum','role:admin']);
Route::post('courses/material-upload',[MaterialController::class,'uploadMaterial'])->middleware(['api','auth:sanctum','role:faculty']);
Route::get('courses/materials/{sectionId}',[MaterialController::class,'getMaterials'])->middleware(['api','auth:sanctum','role:faculty,student']);
Route::get('courses/material/{materialId}',[MaterialController::class,'getMaterial'])->middleware(['api','auth:sanctum','role:faculty,student']);
Route::get('course/enrollments',[CreateEnrollmentController::class,'index'])->middleware(['api','auth:sanctum','role:student']);
Route::post('course/enrollments',[CreateEnrollmentController::class,'store'])->middleware(['api','auth:sanctum','role:student']);
Route::put('course/enrollments',[CreateEnrollmentController::class,'updateEnrollments'])->middleware(['api','auth:sanctum','role:student']);
Route::get('course/all-enrollments/{Studentid}',[CreateEnrollmentController::class,'showallEnrollments'])->middleware(['api','auth:sanctum','role:student']);
Route::get('course/current-enrollments/{Studentid}',[CreateEnrollmentController::class,'showCurrentEnrollments'])->middleware(['api','auth:sanctum','role:student']);
Route::post('/assignments/{assignmentId}/grades/upload', [GradeUploadController::class, 'uploadAssignmentGrades'])->middleware(['api', 'auth:sanctum', 'role:faculty']);
Route::post('course/grades/{courseSectionId}',[UploadCourseGradeController::class,'uploadCourseGrades'])->middleware(['api','auth:sanctum','role:admin']);
Route::post('announcement/create',[AnnouncementController::class,'store'])->middleware(['api','auth:sanctum','role:admin,faculty']);
Route::put('announcement/update/{id}',[AnnouncementController::class,'edit'])->middleware(['api','auth:sanctum','role:admin,faculty']);
Route::delete('announcement/delete/{id}',[AnnouncementController::class,'destroy'])->middleware(['api','auth:sanctum','role:admin,faculty']);
Route::get('announcement/{id}',[AnnouncementController::class,'getAnnouncement'])->middleware(['api','auth:sanctum']);
Route::get('announcement/section/{courseSectionId}',[AnnouncementController::class,'getAnnouncementsForSection'])->middleware(['api','auth:sanctum']);
Route::get('announcement-general',[AnnouncementController::class,'getAllGeneralAnnouncement'])->middleware(['api','auth:sanctum']);
Route::get('announcement',[AnnouncementController::class,'index'])->middleware(['api','auth:sanctum']);