<?php

use App\Http\Controllers\API\V1\Admin\Coursecontroller;
use App\Http\Controllers\API\V1\Admin\CourseSectionControoler;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\API\V1\Admin\UserController;
use App\Http\Controllers\API\V1\Auth\AuthController;
use App\Http\Controllers\API\V1\Auth\PasswardResetController;
use App\Http\Controllers\API\V1\Student\ProfileContoller;
use App\Http\Controllers\API\V1\Faculty\MaterialController;
Route::post('/users', [UserController::class, 'store'])->middleware(['api', 'auth:sanctum', 'role:admin']);
Route::post('edit-user/{id}',[UserController::class, 'edit'])->middleware(['api', 'auth:sanctum', 'role:admin']);
Route::post('delete-user/{id}',[UserController::class, 'delete'])->middleware(['api', 'auth:sanctum', 'role:admin']);
Route::post('/login', [AuthController::class, 'login']);
Route::post('/logout/{id}', [AuthController::class, 'logout'])->middleware(['api', 'auth:sanctum']);
Route::post('/forget-password', [PasswardResetController::class, 'forget']);
Route::post('/reset-password', [PasswardResetController::class, 'reset']);
Route::post('/edit-profile/{id}', [ProfileContoller::class, 'update'])->middleware(['api', 'auth:sanctum', 'role:student']);
Route::post('/course-create',[Coursecontroller::class,'store'])->middleware(['api','auth:sanctum','role:admin']);
 Route::get('/courses',[Coursecontroller::class,'index'])->middleware(['api','auth:sanctum','role:admin']);
 Route::get('/courses/{id}',[Coursecontroller::class,'show'])->middleware(['api','auth:sanctum']);
 Route::post('/course-update/{id}',[Coursecontroller::class,'update'])->middleware(['api','auth:sanctum','role:admin']);
 Route::post('/course-delete/{id}',[Coursecontroller::class,'destroy'])->middleware(['api','auth:sanctum','role:admin']);
 Route::post('course-section-create',[CourseSectionControoler::class,'store'])->middleware(['api','auth:sanctum','role:admin']);
 Route::get('course-sections',[CourseSectionControoler::class,'index'])->middleware(['api','auth:sanctum','role:admin']);
Route::get('course-section/{id}',[CourseSectionControoler::class,'show'])->middleware(['api','auth:sanctum','role:admin']);
Route::post('course-section-update/{id}',[CourseSectionControoler::class,'update'])->middleware(['api','auth:sanctum','role:admin']);
Route::post('course-section-delete/{id}',[CourseSectionControoler::class,'destroy'])->middleware(['api','auth:sanctum','role:admin']);
Route::get('course-sections-current',[CourseSectionControoler::class,'currentSections'])->middleware(['api','auth:sanctum','role:admin']);
Route::post('courses/material-upload',[MaterialController::class,'uploadMaterial'])->middleware(['api','auth:sanctum','role:faculty']);
Route::get('courses/materials/{sectionId}',[MaterialController::class,'getMaterials'])->middleware(['api','auth:sanctum','role:faculty,student']);
Route::get('courses/material/{materialId}',[MaterialController::class,'getMaterial'])->middleware(['api','auth:sanctum','role:faculty,student']);